spring.application.name=pub-sub-queue

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Funções a serem ativadas
spring.cloud.function.definition=processarPedido;notificacaoPedidoProcessado;auditoriaPedidoProcessado;transportePedido;notificacaoPedidoEmTransporte;auditoriaPedidoEmTransporte;entregarPedido;notificacaoPedidoEntregue;auditoriaPedidoEntregue

# Fila de processamento
spring.cloud.stream.bindings.enviarPedido-out-0.destination=fila-processamento-pedidos
spring.cloud.stream.bindings.processarPedido-in-0.destination=fila-processamento-pedidos
spring.cloud.stream.bindings.processarPedido-out-0.destination=pedido-processado

# Notificação e Auditoria consomem a mesma fila
spring.cloud.stream.bindings.notificacaoPedidoProcessado-in-0.destination=pedido-processado
spring.cloud.stream.bindings.auditoriaPedidoProcessado-in-0.destination=pedido-processado

# Vinculações para transporte
spring.cloud.stream.bindings.transportePedido-in-0.destination=pedido-processado
spring.cloud.stream.bindings.transportePedido-out-0.destination=pedido-em-transporte

# Vinculações para entrega
spring.cloud.stream.bindings.entregarPedido-in-0.destination=pedido-em-transporte
spring.cloud.stream.bindings.entregarPedido-out-0.destination=pedido-entregue

spring.cloud.stream.bindings.notificacaoPedidoEmTransporte-in-0.destination=pedido-em-transporte
spring.cloud.stream.bindings.auditoriaPedidoEmTransporte-in-0.destination=pedido-em-transporte

spring.cloud.stream.bindings.notificacaoPedidoEntregue-in-0.destination=pedido-entregue
spring.cloud.stream.bindings.auditoriaPedidoEntregue-in-0.destination=pedido-entregue
